[tool.pylint.messages_control]


disable = [
  "missing-module-docstring",
  "missing-function-docstring",
  "invalid-name",
  "missing-timeout",
  "unused-argument",
  "duplicate-code",
  "unused-variable",
  "unused-import"
]
