services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - MODEL_LOCATION=/app/model
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - /home/azureuser/.aws:/root/.aws:ro
      - ./model:/app/model
