channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=22.2.2
- pip:
  - mlflow
  - mypy-extensions==0.4.3
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - typing-extensions==4.3.0
  - xgboost==1.6.2
name: mlflow-env
